- name: 提交并推送更改
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    git config --global user.name 'github-actions[bot]'
    git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    
    # 显示工作区状态
    echo "========== 工作区状态 =========="
    git status
    
    # 添加指定文件
    git add publicFileIndex.json .github/workflows/package-lock.json
    
    # 检查是否有变更需要提交
    if [[ $(git status --porcelain) ]]; then
      echo "========== 提交变更 =========="
      git commit -m '由Actions自动生成插件市场所需JSON索引'
      
      # 明确指定推送的分支，避免歧义
      git push origin HEAD:main
      
      echo "========== 推送成功 =========="
    else
      echo "没有文件需要提交"
    fi
