name: 生成 插件市场所需 索引

on:
  push:
    paths:
      - 'Adapter/**'
      - 'plugins/**'
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      workflows: write  # 允许修改工作流文件

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 安装依赖
        run: |
          cd $GITHUB_WORKSPACE  # 在仓库根目录安装依赖
          npm install

      - name: 检查目录结构
        run: |
          echo "当前工作目录: $(pwd)"
          ls -l
          if [ -d "plugins" ]; then
            echo "plugins 目录存在"
          else
            echo "错误: plugins 目录不存在"
            exit 1
          fi

      - name: 由Actions自动生成插件市场所需JSON索引
        run: |
          cd $GITHUB_WORKSPACE
          node .github/workflows/generate_index.js

      - name: 提交并推送更改
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          
          # 显示工作区状态
          echo "========== 工作区状态 =========="
          git status
          
          # 添加所有变更文件（包括package-lock.json）
          git add .
          
          # 显示添加后的状态
          echo "========== 添加后的状态 =========="
          git status
          
          # 检查是否有变更需要提交
          if [[ $(git status --porcelain) ]]; then
            echo "========== 提交变更 =========="
            git commit -m '由Actions自动生成插件市场所需JSON索引'
            git push origin HEAD:main  # 明确推送到main分支
            echo "========== 推送成功 =========="
          else
            echo "没有文件需要提交"
          fi

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 2
